exclude:
    - "README.md"
    - "changelog.md"
    - "tests"
    - ".travis.yml"

kramdown:
    input: GFM

sass:
    sass_dir: assets/scss
    style: compressed

author:
    name: "Spencer Julian"
    job: "HPC Systems Administrator"
    bio: "I design, develop, build, and hack small things that operate on a grand scale."
    employer: "Purdue University"
    email: "sj@spencerjulian.com"
    url: "https://spencerjulian.com"
    github: "https://github.com/kuruoujou"
    twitter: "http://twitter.com/kuroshi"
    linkedin: "https://linkedin.com/in/spencerjulian"

title: Spencer Julian
tagline: Hello There!
description: DevOps, Embedded Systems, HPC
baseurl: https://spencerjulian.com

navbar:
    - slug: resume
      title: Résumé
